name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:  
    runs-on: ubuntu-latest
   
    env:      
      DOCKER_REGISTRY: registry.hub.docker.com
      DOCKER_IMAGE: rhernaus/virtunet-x
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}               
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login      
      if: success()      
      run: |        
        echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin 

    - name: Build
      if: success()      
      run: |        
        docker build --tag ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:$(date +%s) .
    
    - name: Push
      if: success()      
      run: |        
        docker push -a ${DOCKER_REGISTRY}/${DOCKER_IMAGE}